# Default values for docker-ui.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: joxit/docker-registry-ui
  tag: static
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

#Environment Variables
env:
  REGISTRY_TITLE: "3GPP-DOCKER-REGISTRY"
  REGISTRY_URL: "http://10.43.118.223:5000"
  DELETE_IMAGES: "true"

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  annotations:
    fabric8.io/expose: "true"
    fabric8.io/ingress.annotations: "kubernetes.io/ingress.class: nginx"
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 400m
    memory: 512Mi

nodeSelector: {}

tolerations: []

affinity: {}
